### ISSUE TITLE
Link to Essay is broken

### ISSUE THREAD

**Issue by MarkowEduard** [ambuc/solitaire#2]
...

**Comment by ambuc** [comment]
Thanks!

**Comment by MarkowEduard** [comment]
This was very fast, many thanks, just finished reading the essay. Awsome work, presentation **and** content wise. Found one typo "but the core of the game take**x** place". Learnt Haskell a couple of weeks ago, now studying monad transformers and lenses. I fully agree with your thoughts about UI and "business logic". Again: Many thanks for this excellent essay and the excemplary implementation of Solitaire.
